************* Module src.unit_test_generator
unit_test_generator.py:465:0: C0301: Line too long (104/100) (line-too-long)
unit_test_generator.py:773:0: C0301: Line too long (128/100) (line-too-long)
unit_test_generator.py:1605:0: C0301: Line too long (107/100) (line-too-long)
unit_test_generator.py:1668:0: C0301: Line too long (109/100) (line-too-long)
unit_test_generator.py:1760:0: C0301: Line too long (114/100) (line-too-long)
unit_test_generator.py:1764:0: C0301: Line too long (180/100) (line-too-long)
unit_test_generator.py:1796:0: C0301: Line too long (107/100) (line-too-long)
unit_test_generator.py:1809:0: C0301: Line too long (102/100) (line-too-long)
unit_test_generator.py:1811:0: C0301: Line too long (122/100) (line-too-long)
unit_test_generator.py:1812:0: C0301: Line too long (120/100) (line-too-long)
unit_test_generator.py:1814:0: C0301: Line too long (127/100) (line-too-long)
unit_test_generator.py:1:0: C0302: Too many lines in module (2010/1000) (too-many-lines)
unit_test_generator.py:323:9: W0511: TODO add a "update_types_in_use" method (fixme)
unit_test_generator.py:415:17: W0511: TODO try/catch/raise exception (fixme)
unit_test_generator.py:452:21: W0511: TODO try/catch/raise exception (fixme)
unit_test_generator.py:484:21: W0511: TODO try/catch/raise exception (fixme)
unit_test_generator.py:493:21: W0511: TODO try/catch/raise exception (fixme)
unit_test_generator.py:990:5: W0511: TODO remove these assserts and the hash_keys set (fixme)
unit_test_generator.py:996:5: W0511: TODO remove this deepcopy (fixme)
unit_test_generator.py:1064:5: W0511: TODO: Find a better way to do this than a str compare! (fixme)
unit_test_generator.py:1093:9: W0511: TODO: Determine if there's ever more than one leading space (fixme)
unit_test_generator.py:1186:13: W0511: TODO: This is (fixme)
unit_test_generator.py:1322:9: W0511: TODO Fix bug here where function_metadata.coverage_io dictionaries (fixme)
unit_test_generator.py:1328:9: W0511: TODO The code below is likely unnecessary now (fixme)
unit_test_generator.py:109:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
unit_test_generator.py:339:15: E1120: No value for argument 'obj' in function call (no-value-for-parameter)
unit_test_generator.py:547:12: W0719: Raising too general exception: Exception (broad-exception-raised)
unit_test_generator.py:628:0: W1113: Keyword argument before variable positional arguments list in the definition of do_the_decorator_thing function (keyword-arg-before-vararg)
unit_test_generator.py:721:19: W0718: Catching too general exception Exception (broad-exception-caught)
unit_test_generator.py:763:20: W0123: Use of eval (eval-used)
unit_test_generator.py:830:11: W0718: Catching too general exception Exception (broad-exception-caught)
unit_test_generator.py:863:15: W0718: Catching too general exception Exception (broad-exception-caught)

------------------------------------------------------------------
Your code has been rated at 9.67/10 (previous run: 9.66/10, +0.01)

