************* Module src.unit_test_generator
unit_test_generator.py:464:0: C0301: Line too long (104/100) (line-too-long)
unit_test_generator.py:768:0: C0301: Line too long (128/100) (line-too-long)
unit_test_generator.py:1436:0: C0301: Line too long (107/100) (line-too-long)
unit_test_generator.py:1748:0: C0301: Line too long (114/100) (line-too-long)
unit_test_generator.py:1753:0: C0301: Line too long (179/100) (line-too-long)
unit_test_generator.py:1755:0: C0301: Line too long (107/100) (line-too-long)
unit_test_generator.py:1764:0: C0301: Line too long (124/100) (line-too-long)
unit_test_generator.py:1765:0: C0301: Line too long (144/100) (line-too-long)
unit_test_generator.py:1766:0: C0301: Line too long (142/100) (line-too-long)
unit_test_generator.py:1768:0: C0301: Line too long (144/100) (line-too-long)
unit_test_generator.py:1769:0: C0301: Line too long (105/100) (line-too-long)
unit_test_generator.py:1770:0: C0301: Line too long (112/100) (line-too-long)
unit_test_generator.py:1828:0: C0301: Line too long (126/100) (line-too-long)
unit_test_generator.py:1834:0: C0301: Line too long (105/100) (line-too-long)
unit_test_generator.py:1:0: C0302: Too many lines in module (1964/1000) (too-many-lines)
unit_test_generator.py:322:9: W0511: TODO add a "update_types_in_use" method (fixme)
unit_test_generator.py:414:17: W0511: TODO try/catch/raise exception (fixme)
unit_test_generator.py:451:21: W0511: TODO try/catch/raise exception (fixme)
unit_test_generator.py:483:21: W0511: TODO try/catch/raise exception (fixme)
unit_test_generator.py:492:21: W0511: TODO try/catch/raise exception (fixme)
unit_test_generator.py:983:5: W0511: TODO remove these assserts and the hash_keys set (fixme)
unit_test_generator.py:989:5: W0511: TODO remove this deepcopy (fixme)
unit_test_generator.py:1057:5: W0511: TODO: Find a better way to do this than a str compare! (fixme)
unit_test_generator.py:1086:9: W0511: TODO: Determine if there's ever more than one leading space (fixme)
unit_test_generator.py:1179:13: W0511: TODO: This is (fixme)
unit_test_generator.py:1315:9: W0511: TODO Fix bug here where function_metadata.coverage_io dictionaries (fixme)
unit_test_generator.py:1321:9: W0511: TODO The code below is likely unnecessary now (fixme)
unit_test_generator.py:109:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
unit_test_generator.py:338:15: E1120: No value for argument 'obj' in function call (no-value-for-parameter)
unit_test_generator.py:546:12: W0719: Raising too general exception: Exception (broad-exception-raised)
unit_test_generator.py:627:0: W1113: Keyword argument before variable positional arguments list in the definition of do_the_decorator_thing function (keyword-arg-before-vararg)
unit_test_generator.py:716:19: W0718: Catching too general exception Exception (broad-exception-caught)
unit_test_generator.py:758:20: W0123: Use of eval (eval-used)
unit_test_generator.py:824:11: W0718: Catching too general exception Exception (broad-exception-caught)
unit_test_generator.py:857:15: W0718: Catching too general exception Exception (broad-exception-caught)
unit_test_generator.py:1553:0: R0913: Too many arguments (7/5) (too-many-arguments)

------------------------------------------------------------------
Your code has been rated at 9.62/10 (previous run: 9.60/10, +0.02)

